agents/urls.py
from django.urls import path
from .views import AgentListView,AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView

urlpatterns=[
 path('',AgentListView.as_view(),name='agent_list'),
 path('create/',AgentCreateView.as_view(),name='agent_create'),
 path('<int:pk>/',AgentDetailView.as_view(),name='agent_detail'), #syntax for primary key in route
 path('<int:pk>/update/',AgentUpdateView.as_view(),name='agent_update'),
 path('<int:pk>/delete/',AgentDeleteView.as_view(),name='agent_delete'),
]

app_name='agents'

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path,include
from leads.views import landing_page,LandingPageView,SignupView
from django.contrib import admin
from django.contrib.auth.views import (PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,
PasswordResetCompleteView)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(),name='landing-page'),
    path('leads/',include('leads.urls',namespace='leads')),
    path('agents/',include('agents.urls',namespace='agents')),
    path('login/',LoginView.as_view(),name='login'),
    path('signup/',SignupView.as_view(),name='signup'),
    path('logout/',LogoutView.as_view(),name='logout'),
    
    path('reset_password/',PasswordResetView.as_view(template_name="leads/password_reset_form.html"),name="reset_password"),
    path('reset_password_done/',PasswordResetDoneView.as_view(template_name="leads/password_reset_done.html"),name="password_reset_done"),
    path('reset_password_confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name="leads/password_reset_confirm.html"),name="password_reset_confirm"),
    path('reset_password_complete/',PasswordResetCompleteView.as_view(template_name="leads/password_reset_complete.html"),name="password_reset_complete"),

    # path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view
    # (template_name="leads/password_reset_done.html"),name="password_reset_complete"),
]

if settings.DEBUG:    # for deployment
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import (LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,
LeadDeleteView,AssignAgentView,CategoryListView,CategoryDetailView,LeadCategoryUpdateView)

urlpatterns = [
    path('',LeadListView.as_view(),name='lead_list'),
    path('<int:pk>/',LeadDetailView.as_view(),name='lead_detail'), #syntax for primary key in route
    path('<int:pk>/update/',LeadUpdateView.as_view(),name='lead_update'),
    path('<int:pk>/delete/',LeadDeleteView.as_view(),name='lead_delete'),
    path('create/',LeadCreateView.as_view(),name='lead_create'), #syntax for primary key in route
    path('<int:pk>/assign_agent/',AssignAgentView.as_view(),name='assign_agent'),
    path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name='lead_category_update'),
    path('categories/',CategoryListView.as_view(),name='category_list'), 
    path('categories/<int:pk>/',CategoryDetailView.as_view(),name='category_detail'), 
]

app_name='leads'

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_save,post_save
# from django.contrib.auth import get_user_model 

# User=get_user_model() #A function for custom user model
class User(AbstractUser):
    is_organiser=models.BooleanField(default=True)
    is_agent=models.BooleanField(default=False)

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



class Lead(models.Model):
    # SOURCE_CHOICES=(
    #     ('Youtube','Youtube'), #first value is stored in db,2nd is displayed on screen
    #     ('Google','Google'),
    #     ('Newsletter','Newsletter'),
    # )
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    age=models.IntegerField(default=0)
    organisation=models.ForeignKey(Profile,on_delete=models.CASCADE)#to keep track of leads within an organisation
    agent=models.ForeignKey("Agent",null=True,blank=True,on_delete=models.SET_NULL)
    category=models.ForeignKey("Category",related_name="leads",null=True,blank=True,on_delete=models.SET_NULL)
    description=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    #live tracker of date and time
    
    phone_number=models.CharField(max_length=20)
    email=models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

    # phoned=models.BooleanField(default=False)
    # source=models.CharField(choices=SOURCE_CHOICES,max_length=100)

    # profile_picture=models.ImageField(blank=True,null=True) blank means ' ',null means nothing
    # special_files=models.FileField(blank=True,null=True) files are not uploaded into db


class Category(models.Model):
    name=models.CharField(max_length=30) #New,Contacted,Converted,Unconverted
    organisation=models.ForeignKey(Profile,on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.name}"

class Agent(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    organisation=models.ForeignKey(Profile,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
       Profile.objects.create(user=instance)

post_save.connect(post_user_created_signal,sender=User)

leads/forms.py
from django import forms
from .models import Lead,Agent
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm,UsernameField

User=get_user_model()
class LeadModelForm(forms.ModelForm): # easier to work with model forms 
    class Meta:
        model=Lead
        fields=(
            'first_name','last_name','age','agent','description',
            'phone_number','email',
        )
    
class LeadForm(forms.Form):
    first_name=forms.CharField()
    last_name=forms.CharField()
    age=forms.IntegerField(min_value=0)

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","email")
        # field_classes = {'username': UsernameField}
class AssignAgentForm(forms.Form):
    agent=forms.ModelChoiceField(queryset=Agent.objects.none())
    
   # for dynamic display of agents
    def __init__(self, *args, **kwargs):
        request=kwargs.pop("request")
        agents=Agent.objects.filter(organisation=request.user.profile)
        super(AssignAgentForm,self).__init__(*args,**kwargs) # to instantiate the form
        self.fields["agent"].queryset=agents

class LeadCategoryUpdateForm(forms.ModelForm):
      class Meta:
        model=Lead
        fields=(
            'category',
        )
    

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from agents.mixins import OrganiserAndLoginRequiredMixin
# class based views
from .forms import LeadForm,LeadModelForm,CustomUserCreationForm,AssignAgentForm,LeadCategoryUpdateForm
# Create your views here.

#CRUD-Create,Read,Update,Delete+List
#mixins allows us to check if a user is logged in:if user is not logged in then redirects to login

from .models import Lead,Agent,Category

class SignupView(generic.CreateView):
    template_name= "registration/signup.html"
    form_class=CustomUserCreationForm
    
    def get_success_url(self):
        return reverse("login")

class LandingPageView(generic.TemplateView):
    template_name="leads/landing.html"

def landing_page(request):
    return render(request,'leads/landing.html')

class LeadListView(LoginRequiredMixin,generic.ListView):
    template_name="leads/lead_list.html"
    context_object_name="leads" #By default name of context is object_list,so we can modify it by this line
    
    #Assigned querysets
    def get_queryset(self):
        user=self.request.user

        #Initial queryset of leads for entire organisation
        if user.is_organiser:
            queryset=Lead.objects.filter(organisation=user.profile,agent__isnull=False)
        else:
            queryset=queryset=Lead.objects.filter(organisation=user.agent.organisation,agent__isnull=False)
            #filter for the agent who is logged in
            queryset=queryset.filter(agent__user=user) #user within agent model
        return queryset


    #Unassigned querysets
    def get_context_data(self,**kwargs):
        context=super(LeadListView,self).get_context_data(**kwargs)# to get already existing context data from leadlist class
        user=self.request.user
        if user.is_organiser:
            queryset=Lead.objects.filter(organisation=user.profile,agent__isnull=True)
            context.update({
                "unassigned_leads":queryset
           })
        return context

def lead_list(request):
    leads=Lead.objects.all()
    context={
        "leads":leads
    }
    return render(request,'leads/lead_list.html',context)


class LeadDetailView(LoginRequiredMixin,generic.DetailView):
    template_name="leads/lead_detail.html"
    context_object_name="lead" 

    def get_queryset(self):
        user=self.request.user

        #Initial queryset of leads for entire organisation
        if user.is_organiser:
            queryset=Lead.objects.filter(organisation=user.profile)
        else:
            queryset=queryset=Lead.objects.filter(organisation=user.agent.organisation)
            #filter for the agent who is logged in
            queryset=queryset.filter(agent__user=user) #user within agent model
        return queryset


def lead_detail(request,pk):
    lead=Lead.objects.get(id=pk)
    context={
        "lead":lead
    }
    return render(request,'leads/lead_detail.html',context)


class LeadCreateView(OrganiserAndLoginRequiredMixin,generic.CreateView):
    template_name="leads/lead_create.html"
    form_class=LeadModelForm
    
    def get_success_url(self):
        return reverse("leads:lead_list") #lead_list is name of url

    def form_valid(self,form):
        lead=form.save(commit=False)
        lead.organisation=self.request.user.profile
        lead.save()
        #TODO send email
        send_mail(
            
            subject="A lead has been created.",
            message="Go to the site",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        return super(LeadCreateView,self).form_valid(form) #Continue with LeadCreateView after sending email


def lead_create(request):
    form=LeadModelForm()
    if(request.method=="POST"):
        form=LeadModelForm(request.POST)
        if form.is_valid():
            form.save() #for directly pushing the data into Lead model
            return redirect('/leads')
    context={
        "form":form
    }
    return render(request,'leads/lead_create.html',context)



class LeadUpdateView(OrganiserAndLoginRequiredMixin,generic.UpdateView):
    template_name="leads/lead_update.html"
    form_class=LeadModelForm
    def get_queryset(self):
        user=self.request.user
        #Initial queryset of leads for entire organisation
        #Already know that the user is an organisor
        return Lead.objects.filter(organisation=user.profile)
    
    def get_success_url(self):
        return reverse("leads:lead_list")


def lead_update(request,pk):
    lead=Lead.objects.get(id=pk)
    form =LeadModelForm(instance=lead) #for updating a particular instance of Lead model while saving
    if(request.method=="POST"):
        form=LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context={
        "form":form,
        "lead":lead
    }
    return render(request,'leads/lead_update.html',context)


class LeadDeleteView(OrganiserAndLoginRequiredMixin,generic.DeleteView):
    template_name="leads/lead_delete.html"

    def get_queryset(self):
        user=self.request.user
        #Initial queryset of leads for entire organisation
        #Already know that the user is an organisor
        return Lead.objects.filter(organisation=user.profile)
    
    def get_success_url(self):
        return reverse("leads:lead_list")


def lead_delete(request,pk):
    lead=Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/leads')


class CategoryListView(LoginRequiredMixin,generic.ListView):
    template_name='leads/category_list.html'
    context_object_name='category_list'
    
    def get_context_data(self,**kwargs):
        context=super(CategoryListView,self).get_context_data(**kwargs)
        user=self.request.user

        if user.is_organiser:
            queryset=Lead.objects.filter(organisation=user.profile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)

        
        context.update({
            "unassigned_lead_count": queryset.filter(category__isnull=True).count()
        })

        return context

    def get_queryset(self):
        user=self.request.user

        #Initial queryset of leads for entire organisation
        if user.is_organiser:
            queryset=Category.objects.filter(organisation=user.profile)
        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation)
        return queryset

class CategoryDetailView(LoginRequiredMixin,generic.DetailView):
    template_name='leads/category_detail.html'
    context_object_name='category'
    
    # def get_context_data(self,**kwargs):  do this within the template
    #     context=super(CategoryDetailView,self).get_context_data(**kwargs)

    #     qs=Lead.objects.filter(category=self.get_object())
    #     (get_object() is a part of DetailView and it fetches the context object we are working 
    #     with(here category))

    #     leads=self.get_object().leads.all()
    #     (this filters out all the leads within this particular category.Lead ->Category(Many->One)
    #     This special syntax is allowed only because category is a fk in leads model.
    #     leads is related_name in lead model for Category)

        
    #     context.update({
    #         "leads":leads
    #     })

    #     return context

    def get_queryset(self):
        user=self.request.user

        #Initial queryset of leads for entire organisation
        if user.is_organiser:
            queryset=Category.objects.filter(organisation=user.profile)
        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation)
        return queryset




class AssignAgentView(OrganiserAndLoginRequiredMixin,generic.FormView):
    template_name="leads/assign_agent.html"
    form_class=AssignAgentForm

    def get_form_kwargs(self,**kwargs):
        kwargs=super(AssignAgentView,self).get_form_kwargs(**kwargs)

        kwargs.update({
            "request":self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self,form):
        agent=form.cleaned_data["agent"]
        lead=Lead.objects.get(id=self.kwargs["pk"])
        lead.agent=agent
        lead.save()
        return super(AssignAgentView,self).form_valid(form)

class LeadCategoryUpdateView(LoginRequiredMixin,generic.UpdateView):
    template_name="leads/lead_category_update.html"
    form_class=LeadCategoryUpdateForm
    def get_queryset(self):
        user=self.request.user

        #Initial queryset of leads for entire organisation
        if user.is_organiser:
            queryset=Lead.objects.filter(organisation=user.profile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
         # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    
    def get_success_url(self):
        return reverse("leads:lead_detail", kwargs={"pk": self.get_object().id})
        #self.get_object() refers to a particular lead
        #kwargs helps in passing pk to url

#     def lead_update(request,pk):
#     lead=Lead.objects.get(id=pk)
#     form=LeadForm()
#     if(request.method=="POST"):
#         form=LeadForm(request.POST)
#         if form.is_valid():
#             first_name=form.cleaned_data['first_name']
#             last_name=form.cleaned_data['last_name']
#             age=form.cleaned_data['age']
#             lead.first_name=first_name,
#             lead.last_name=last_name,
#             lead.age=age,
#             return redirect('/leads')
#     context={
#         "form":form,
#         "lead":lead
#     }

leads/templates/leads/assign_agent.html
{% extends "leads/base.html" %}
{% block content %}
    <a href="{%url 'leads:lead_list' %}">BACK TO LEADS :)</a>
    <hr>
    <h1>Assign an Agent to this lead</h1>
    <div>
        <form action="." method="post">
            {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
    </div>
</body>
</html>
{% endblock content %}

leads/templates/leads/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leadify</title>
    <link href="{% static 'css/styles.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class="max-w-7xl mx-auto">
      <header class="text-gray-600 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">LEADIFY</span>
          </a>
          <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            {% if not request.user.is_authenticated %}
              <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
            {% else %}
              {% if request.user.is_organiser %}
              <a href="{% url 'agents:agent_list' %}" class="mr-5 hover:text-gray-900">Agents</a>
              {% endif %}
              <a href="{% url 'leads:lead_list' %}" class="mr-5 hover:text-gray-900">Leads</a>
            {% endif %}
          </nav>
          {% if request.user.is_authenticated %}
             Logged in as: {{request.user.username}}
            <a href="{%url 'logout'%}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
              Logout
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
          {% else %}
          <a href="{%url 'login'%}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
              Login
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
          {% endif %}
        </div>
      </header>
        {%block content%}
        {%endblock content%}
    </div>
    
</body>
</html>

leads/templates/leads/category_list.html
{% extends "leads/base.html" %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These categories segment the leads
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td class="px-4 py-3">Unassigned Leads</td>
                <td class="px-4 py-3">{{unassigned_lead_count}}</td>
              </tr>
              {% for category in category_list %}
              <tr>
                <td class="px-4 py-3">
                  <a href="{% url 'leads:category_detail' category.pk%}">{{category.name}}</a>
                </td>
                <td class="px-4 py-3">Gugu</td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "leads/base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:lead_detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'leads:lead_category_update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Category
                </a>
                <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/lead_create.html
{% extends "leads/base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead_list' %}">Go back to leads</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new lead</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "leads/base.html" %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
          <div class="flex mb-4">
            <a href="{%url 'leads:lead_detail' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Overview
            </a>
            <a href="{%url 'leads:lead_category_update' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Category
            </a>
            <a href="{%url 'leads:lead_update' lead.pk %}"
              class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Update Details
            </a>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{lead.age}}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">{{lead.email}}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Phone Number</span>
            <span class="ml-auto text-gray-900">{{lead.phone_number}}</span>
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
    <a href="{%url 'leads:lead_list' %}">BACK :)</a>
    <hr>
       <h1>{{lead.first_name}}</h1>
       <p>{{lead.age}}</p>
       <p>Agent-{{lead.agent}}</p>
       <hr>
       <a href="{%url 'leads:lead_update' lead.pk %}">Update</a>
       <a href="{%url 'leads:lead_delete' lead.pk %}">Delete</a>
{% endblock content %}

leads/templates/leads/lead_update.html
  {% extends "leads/base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:lead_detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'leads:lead_category_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Category
                </a>
                <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'leads:lead_delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/password_reset_complete.html
{% extends 'leads/base.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login</a> now.
  </p>
{% endblock content %}